import { Club } from "@/types";

export const clubs: Club[] = [
  {
    id: "high-stakes-society",
    name: "High Stakes Society",
    location: {
      area: "Jayanagar",
      city: "Bangalore",
      address: "no. 433, 30/1, 28th Cross Rd, Geetha Colony, 4th T Block East, 4th Block, Jayanagar, Bengaluru, Karnataka 560011",
      coordinates: {
        lat: 12.9279,
        lng: 77.5871,
      },
    },
    description: "High Stakes Society is a premium poker destination in Jayanagar offering professionally managed tables with state-of-the-art facilities.",
    images: [
      "/images/high1.jpg",
      "/images/high2.jpeg",
      "/images/high3.jpeg",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 9606991796",
      email: "contact@highstakessociety.com",
      website: "https://www.highstakessociety.com",
    },
    operatingHours: [
      { day: "Monday", open: "11:00", close: "23:00" },
      { day: "Tuesday", open: "11:00", close: "23:00" },
      { day: "Wednesday", open: "11:00", close: "23:00" },
      { day: "Thursday", open: "11:00", close: "23:00" },
      { day: "Friday", open: "11:00", close: "23:00" },
      { day: "Saturday", open: "11:00", close: "23:00" },
      { day: "Sunday", open: "11:00", close: "23:00" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 6,
      totalPlayers: 48,
      waitingList: 3,
      expectedWaitTime: 20,
      nextCallTime: "19:30",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 4,
          players: 32,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 2,
          players: 16,
        },
      ],
    },
  },
  {
    id: "indian-poker-house",
    name: "Indian Poker House",
    location: {
      area: "Jayanagar",
      city: "Bangalore",
      address: "5Th floor, 251/62, 24th Main Rd, Jayanagar 9th Block East, 5th Block, Jayanagar, Bengaluru, Karnataka 56004",
      coordinates: {
        lat: 12.9279,
        lng: 77.5871,
      },
    },
    description: "Indian Poker House is a premier poker destination in Jayanagar offering a sophisticated gaming environment with professional tables and excellent service.",
    images: [
      "/images/ind3.png",
      "/images/ind2.png",
      "/images/ind1.png",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 7411293003",
      email: "info@indianpokerhouse.com",
      website: "https://www.indianpokerhouse.com",
    },
    operatingHours: [
      { day: "Monday", open: "11:00", close: "23:00" },
      { day: "Tuesday", open: "11:00", close: "23:00" },
      { day: "Wednesday", open: "11:00", close: "23:00" },
      { day: "Thursday", open: "11:00", close: "23:00" },
      { day: "Friday", open: "11:00", close: "23:00" },
      { day: "Saturday", open: "11:00", close: "23:00" },
      { day: "Sunday", open: "11:00", close: "23:00" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 5,
      totalPlayers: 40,
      waitingList: 2,
      expectedWaitTime: 15,
      nextCallTime: "20:00",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 2,
          players: 16,
        },
      ],
    },
  },
  {
    id: "the-house-poker",
    name: "The House Poker",
    location: {
      area: "Saint Mark's Road",
      city: "Bangalore",
      address: "3rd Floor - No T, Old No - 13/14, 307, Papanna Street, off Saint Mark's Road, Bengaluru, Karnataka 560001",
      coordinates: {
        lat: 12.9719,
        lng: 77.6119,
      },
    },
    description: "The House Poker offers a premium poker experience in the heart of Bangalore with late-night gaming hours and professional facilities.",
    images: [
      "/images/house2.png",
      "/images/house4.png",
      "/images/house3.png",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 7483418549",
      email: "info@thehousepoker.com",
      website: "https://www.thehousepoker.com",
    },
    operatingHours: [
      { day: "Monday", open: "12:30", close: "02:00" },
      { day: "Tuesday", open: "12:30", close: "02:00" },
      { day: "Wednesday", open: "12:30", close: "02:00" },
      { day: "Thursday", open: "12:30", close: "02:00" },
      { day: "Friday", open: "12:30", close: "02:00" },
      { day: "Saturday", open: "12:30", close: "02:00" },
      { day: "Sunday", open: "12:30", close: "02:00" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 4,
      totalPlayers: 32,
      waitingList: 2,
      expectedWaitTime: 15,
      nextCallTime: "20:00",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 1,
          players: 8,
        },
      ],
    },
  },
  {
    id: "tilt-poker-room",
    name: "Tilt Poker Room",
    location: {
      area: "Indiranagar",
      city: "Bangalore",
      address: "4th floor, Panasonic Building, 233, 80 Feet Rd, Defence Colony, Indiranagar, Bengaluru, Karnataka 560038",
      coordinates: {
        lat: 12.9784,
        lng: 77.6408,
      },
    },
    description: "Tilt Poker Room offers 24/7 poker gaming in a premium location within the Panasonic Living Showroom, featuring state-of-the-art facilities and professional service.",
    images: [
      "/images/tt2.png",
      "/images/tt2.png",
      "/images/tt3.png",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 8553121519",
      email: "info@tiltpokerroom.com",
      website: "https://www.tiltpokerroom.com",
    },
    operatingHours: [
      { day: "Monday", open: "00:00", close: "23:59" },
      { day: "Tuesday", open: "00:00", close: "23:59" },
      { day: "Wednesday", open: "00:00", close: "23:59" },
      { day: "Thursday", open: "00:00", close: "23:59" },
      { day: "Friday", open: "00:00", close: "23:59" },
      { day: "Saturday", open: "00:00", close: "23:59" },
      { day: "Sunday", open: "00:00", close: "23:59" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 6,
      totalPlayers: 48,
      waitingList: 3,
      expectedWaitTime: 20,
      nextCallTime: "19:30",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 4,
          players: 32,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 2,
          players: 16,
        },
      ],
    },
  },
  {
    id: "golden-aces",
    name: "Golden Aces - Legal Poker Room",
    location: {
      area: "Koramangala",
      city: "Bangalore",
      address: "22, Esares building, 80, 100 Feet Rd, S.T. Bed, Cauvery Colony, Koramangala, Bengaluru, Karnataka 560034",
      coordinates: {
        lat: 12.9347,
        lng: 77.6205,
      },
    },
    description: "Golden Aces is a 24/7 legal poker room in Koramangala offering a premium gaming experience with professional tables and excellent service.",
    images: [
      "/images/ga1.png",
      "/images/ga2.png",
      "/images/ga3.png",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 9731131133",
      email: "info@goldenaces.com",
      website: "https://www.goldenaces.com",
    },
    operatingHours: [
      { day: "Monday", open: "00:00", close: "23:59" },
      { day: "Tuesday", open: "00:00", close: "23:59" },
      { day: "Wednesday", open: "00:00", close: "23:59" },
      { day: "Thursday", open: "00:00", close: "23:59" },
      { day: "Friday", open: "00:00", close: "23:59" },
      { day: "Saturday", open: "00:00", close: "23:59" },
      { day: "Sunday", open: "00:00", close: "23:59" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 5,
      totalPlayers: 40,
      waitingList: 2,
      expectedWaitTime: 15,
      nextCallTime: "20:00",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 2,
          players: 16,
        },
      ],
    },
  },
  {
    id: "champs-of-aces",
    name: "Champs of Aces",
    location: {
      area: "Koramangala",
      city: "Bangalore",
      address: "41, 100 Feet Rd, above Reimagine, KHB Colony, 4th Block, Koramangala, Bengaluru, Karnataka 56003",
      coordinates: {
        lat: 12.9716,
        lng: 77.5946,
      },
    },
    description: "Champs of Aces is a premier poker destination offering professional gaming tables and excellent service.",
    images: [
      "/images/ch1.png",
      "/images/ch2.png",
      "/images/ch3.png",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "+91 7010955451",
      email: "info@champsofaces.com",
      website: "https://www.champsofaces.com",
    },
    operatingHours: [
      { day: "Monday", open: "11:00", close: "23:00" },
      { day: "Tuesday", open: "11:00", close: "23:00" },
      { day: "Wednesday", open: "11:00", close: "23:00" },
      { day: "Thursday", open: "11:00", close: "23:00" },
      { day: "Friday", open: "11:00", close: "23:00" },
      { day: "Saturday", open: "11:00", close: "23:00" },
      { day: "Sunday", open: "11:00", close: "23:00" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 4,
      totalPlayers: 32,
      waitingList: 2,
      expectedWaitTime: 15,
      nextCallTime: "20:00",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 1,
          players: 8,
        },
      ],
    },
  },
  {
    id: "royal-flush-poker",
    name: "Royal Flush Poker Room",
    location: {
      area: "Konark",
      city: "Bangalore",
      address: "Konark Vegetarian Restaurant, Konark, Bangalore, Karnataka",
      coordinates: {
        lat: 12.9690131,
        lng: 77.6021938,
      },
    },
    description: "Royal Flush Poker Room offers 24/7 poker gaming with multiple stake levels and professional facilities.",
    images: [
      "/images/royal flush poker room_main.jpg",
      "/images/royal flush poker room1.jpg",
      "/images/royal flush poker room2.jpg",
    ],
    video: "/royal_flush.mp4",
    stakes: [
      {
        name: "Low Stakes",
        smallBlind: 50,
        bigBlind: 100,
        minBuyIn: 5000,
        maxBuyIn: 20000,
        currency: "₹",
      },
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 200,
        bigBlind: 500,
        minBuyIn: 20000,
        maxBuyIn: 100000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "++91 63624 77837",
      email: "info@royalflushpoker.com",
      website: "https://www.royalflushpoker.com",
    },
    operatingHours: [
      { day: "Monday", open: "00:00", close: "23:59" },
      { day: "Tuesday", open: "00:00", close: "23:59" },
      { day: "Wednesday", open: "00:00", close: "23:59" },
      { day: "Thursday", open: "00:00", close: "23:59" },
      { day: "Friday", open: "00:00", close: "23:59" },
      { day: "Saturday", open: "00:00", close: "23:59" },
      { day: "Sunday", open: "00:00", close: "23:59" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 6,
      totalPlayers: 48,
      waitingList: 3,
      expectedWaitTime: 20,
      nextCallTime: "19:30",
      games: [
        {
          stakeId: "Low Stakes",
          tablesRunning: 2,
          players: 16,
        },
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 1,
          players: 8,
        },
      ],
    },
  },
  {
    id: "kings-and-queens-poker",
    name: "Kings And Queens Poker",
    location: {
      area: "Koramangala",
      city: "Bangalore",
      address: "4th Block, 1, 981, 80 Feet Rd, Maharaja Signal, AVS Layout, Koramangala, Bengaluru, Karnataka 560034",
      coordinates: {
        lat: 12.9349239,
        lng: 77.6295192,
      },
    },
    description: "Kings And Queens Poker is a premier 24/7 poker destination in Koramangala offering professional gaming tables and excellent service in a sophisticated environment.",
    images: [
      "/images/kings2.png",
      "/images/kings1.png",
      "/images/kings3.jpeg",
    ],
    stakes: [
      {
        name: "Regular Tables",
        smallBlind: 100,
        bigBlind: 200,
        minBuyIn: 10000,
        maxBuyIn: 40000,
        currency: "₹",
      },
      {
        name: "High Stakes",
        smallBlind: 500,
        bigBlind: 1000,
        minBuyIn: 50000,
        maxBuyIn: 200000,
        currency: "₹",
      },
    ],
    contactInfo: {
      phone: "080 4194 7385",
      email: "info@kingsandqueenspoker.com",
      website: "https://www.kingsandqueenspoker.com",
    },
    operatingHours: [
      { day: "Monday", open: "00:00", close: "23:59" },
      { day: "Tuesday", open: "00:00", close: "23:59" },
      { day: "Wednesday", open: "00:00", close: "23:59" },
      { day: "Thursday", open: "00:00", close: "23:59" },
      { day: "Friday", open: "00:00", close: "23:59" },
      { day: "Saturday", open: "00:00", close: "23:59" },
      { day: "Sunday", open: "00:00", close: "23:59" },
    ],
    amenities: [
      "Professional dealers",
      "Premium bar",
      "Restaurant",
      "Valet parking",
      "Security",
      "VIP rooms",
    ],
    liveStatus: {
      lastUpdated: new Date().toISOString(),
      tablesRunning: 5,
      totalPlayers: 40,
      waitingList: 2,
      expectedWaitTime: 15,
      nextCallTime: "20:00",
      games: [
        {
          stakeId: "Regular Tables",
          tablesRunning: 3,
          players: 24,
        },
        {
          stakeId: "High Stakes",
          tablesRunning: 2,
          players: 16,
        },
      ],
    },
  },
];

export const getClubById = (id: string): Club | undefined => {
  return clubs.find(club => club.id === id);
};

export const getClubsByCity = (city: string): Club[] => {
  return clubs.filter(club => club.location.city.toLowerCase() === city.toLowerCase());
};
